### ISSUE TITLE
is there any usage method ?

### ISSUE THREAD

**Issue by bau720123** [ratkop/-cordova-imagePickerEx#1]
is there any usage method ?
because of there us no detail document
https://github.com/ratkop/-cordova-imagePickerEx/blob/a97a849/README.md

**Comment by ratkop** [comment]
The usage of the plugin is the same as the https://github.com/wymsee/cordova-imagePicker/blob/1ec4242c4f15d83a1842f0439dbb642d5c730773/README.md . The only difference is that it returns double array which contains images that are optimizes+non-optimized. When you call the window.imagePicker.getPictures the result can be used like
for (var i = 0; i < results.length; i=i+2) {
                        thumbnails.push(results[i+1]);
                        images.push(results[i]);
                    }
I'm still having issues with the code for iOS

**Comment by bau720123** [comment]
got it
thanks @ratkop

**Comment by wabsa** [comment]
my app crashed when i'm trying to select an image more than 9mb. any idea to fix this? thanks
