### ISSUE TITLE
Not Compiling

### ISSUE THREAD

**Issue by brizdotdev** [ratkop/-cordova-imagePickerEx#8]
I am trying to use this plugin in an Ionic/Cordova project and when I add the plugin, I get a compilation error.
![comp_err](https://cloud.githubusercontent.com/assets/7137469/9984502/103fa3f0-605c-11e5-8e11-fc63eef80933.png)

**Comment by andrzey** [comment]
I get the same error.

**Comment by jungleBadger** [comment]
I'm facing this issue also. Tried to apply the patch but didn`t work

**Comment by OTSimple** [comment]
I get the same error.

**Comment by jungleBadger** [comment]
Through the Belkacea support I was able to get rid of this issue, I will share with you:

<img width="665" alt="screenshot 2016-01-09 17 42 48" src="https://cloud.githubusercontent.com/assets/12788435/12217987/7e2c9718-b6f8-11e5-96a9-622ff3fc2481.png">

and after that you can install and get running perhaps you can face an issue that you can not select the pictures and send it on android, and again with owner support:

https://github.com/ratkop/-cordova-imagePickerEx/issues/5
https://github.com/b-alidra/-cordova-imagePickerEx/commit/240e25ae356e4f189714c6125bbf3d5bf9041479

**Comment by OTSimple** [comment]
Your solution works very well. Thanks

**Comment by rodrigorellana** [comment]
thank you guys!!!
